// This file will be auto-generated by Convex CLI
// Run `npx convex dev` to generate the real implementation

// Placeholder types
export type QueryCtx = {
  db: any;
};

export type MutationCtx = {
  db: any;
};

// Placeholder function factories
export function query<Args, Returns>(config: {
  args: Args;
  handler: (ctx: QueryCtx, args: any) => Promise<Returns>;
}) {
  return config;
}

export function mutation<Args, Returns>(config: {
  args: Args;
  handler: (ctx: MutationCtx, args: any) => Promise<Returns>;
}) {
  return config;
}
